# Generated by Django 5.0.1 on 2024-01-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
